# Copyright Gammadata GmbH. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
ARG ODOO_VERSION=18.0
ARG ODOO_RELEASE=20251222

FROM odoo:${ODOO_VERSION}-${ODOO_RELEASE}

USER root
ARG ADDON_PATH="/mnt/extra-addons"

RUN apt-get update -y
RUN apt-get install -y build-essential && \
    apt-get install -y  libcairo2-dev && \
    apt-get install -y  pkg-config && \
    apt-get install -y  python3-dev

RUN cat /etc/passwd && \
    cat /etc/group

USER odoo
COPY additional-requirements-18.txt /tmp/additional-requirements.txt
RUN echo "------------- python module lib before install --------------" && \
    which pip3 && \
    pip3 list
RUN python3 -m pip config set global.break-system-packages true
RUN pip3 install -r /tmp/additional-requirements.txt

